// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-Lz76_TiadCwMvRcfXC3GkvxOahRM8Q4',
    appId: '1:281261605407:web:1102767436bbb6d71c4b2a',
    messagingSenderId: '281261605407',
    projectId: 'side-street-eb65e',
    authDomain: 'side-street-eb65e.firebaseapp.com',
    storageBucket: 'side-street-eb65e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHp_lazIkVkOIXxygqmRWa-AN_qg_eYII',
    appId: '1:281261605407:android:e59dbfea3623b9c31c4b2a',
    messagingSenderId: '281261605407',
    projectId: 'side-street-eb65e',
    storageBucket: 'side-street-eb65e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNAiI0tfa64a-PkYqO7Yi81_m5ssohsUU',
    appId: '1:281261605407:ios:2208b46f8c66a1711c4b2a',
    messagingSenderId: '281261605407',
    projectId: 'side-street-eb65e',
    storageBucket: 'side-street-eb65e.firebasestorage.app',
    iosBundleId: 'com.kennymejia.sideStreet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNAiI0tfa64a-PkYqO7Yi81_m5ssohsUU',
    appId: '1:281261605407:ios:2208b46f8c66a1711c4b2a',
    messagingSenderId: '281261605407',
    projectId: 'side-street-eb65e',
    storageBucket: 'side-street-eb65e.firebasestorage.app',
    iosBundleId: 'com.kennymejia.sideStreet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-Lz76_TiadCwMvRcfXC3GkvxOahRM8Q4',
    appId: '1:281261605407:web:93b73546edece2691c4b2a',
    messagingSenderId: '281261605407',
    projectId: 'side-street-eb65e',
    authDomain: 'side-street-eb65e.firebaseapp.com',
    storageBucket: 'side-street-eb65e.firebasestorage.app',
  );
}
